import licenseData from '../assets/licenses.json';
import {
    Accordion,
    AccordionDetails,
    AccordionSummary,
    Box,
    Chip,
    Link,
    List,
    ListItem,
    ListItemText,
    Paper,
    Typography
} from '@mui/material';
import CodeIcon from '@mui/icons-material/Code';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import LinkIcon from '@mui/icons-material/Link';

interface LicensePackage {
    licenses: string;
    repository: string;
    publisher?: string;
    licenseText: string;
    name?: string;
}

const Licenses = () => {
    // Transform the data object into an array
    const licenses = Object.keys(licenseData).map((key: any) => ({
        ...licenseData[key as keyof typeof licenseData],
    }));

    return (
        <Box sx={{
            width: "100%", height: "100%",
            bgcolor: "primary.main", overflowY: "auto", display: "flex", alignItems: "center", flexDirection: "column", scrollbarGutter: 'stable',
        }}>
            {/* Page Header */}
            <Box>
                <Typography variant="h4" component="h1" fontWeight="bold" gutterBottom>
                    Privacy Policy and Software Licenses
                </Typography>
                <Typography variant="h6" component="h1" fontWeight="bold" gutterBottom>
                    Effective Date: 21.11.2025
                </Typography>
            </Box>

            <Box sx={{ paddingTop: 3, paddingBottom: 2, paddingLeft: "25px", paddingRight: "25px" }}>
                <Typography variant="h5" component="h1" fontWeight="bold" gutterBottom>
                    Privacy Policy
                </Typography>
                <List component={"ol"} sx={{
                    listStyleType: 'decimal',
                    pl: 4,
                    '& .MuiListItem-root': {
                        display: 'list-item',
                    }
                }}>
                    <ListItem>
                        <ListItemText>
                            Welcome to Highpercube! We respect your privacy and are committed to protecting your personal data. This privacy policy explains
                            how we handle your data when you use our speedcubing timer application.
                        </ListItemText>
                    </ListItem>
                    <ListItem>
                        <ListItemText>
                            Information We Collect: We collect the following types of information:

                            {/* Account Information (If applicable): When you create an account, we collect your [Email Address, Username]. */}

                            Solve Data: We store the data generated by your timer usage, including:
                            Solve times and status (Valid, DNF, +2), Scramble sequences, Dates and timestamps, Corresponding session and event values.
                            <br></br>
                            Technical Data: Our servers automatically log information such as your IP address, browser type, and operating system for security and debugging purposes.
                        </ListItemText>
                    </ListItem>
                    <ListItem>
                        <ListItemText>
                            How We Use Your Information: We use your data solely to:

                            Provide and maintain the functionality of the timer.

                            Sync your solve history across multiple devices.

                            Calculate statistics (Average of 5, Average of 12, ...).
                        </ListItemText>
                    </ListItem>
                    <ListItem>
                        <ListItemText>
                            Data Storage and Third Parties: We do not sell your data. However, we use trusted third-party service providers to host our application and
                            database. Your data is stored with:
                            <br></br>
                            [Postgres]: For storing solve data.
                            <br></br>
                            [Strato]: For hosting the website infrastructure.
                        </ListItemText>
                    </ListItem>
                    <ListItem>
                        <ListItemText>
                            Data Retention: We retain your solve data indefinitely so that you can access your complete
                            solve history. You may request the deletion of your account and all associated data at any time.
                        </ListItemText>
                    </ListItem>
                    <ListItem>
                        <ListItemText>
                            Your Rights: Depending on your location, you may have the right to:
                            <br></br>
                            Access: Request a copy of all data we hold about you (usually an export of your solves).
                            <br></br>
                            Deletion (Right to be Forgotten): Request that we delete your account and all solve data from our servers.
                            <br></br>
                            Rectification: Correct inaccurate data.
                        </ListItemText>
                    </ListItem>
                    <ListItem>
                        <ListItemText>
                            Contact Us: If you have questions or wish to exercise your data rights, please contact us at: [highpercube@gmail.com].
                        </ListItemText>
                    </ListItem>
                </List>
            </Box>

            <Box sx={{ paddingTop: 3, paddingBottom: 2 }}>
                <Typography variant="h5" component="h1" fontWeight="bold" gutterBottom>
                    Software Licenses
                </Typography>
                <Typography variant="body1" color="text.primary">
                    The following third-party software is used in this project.
                    Click on a package to view its license details.
                </Typography>
            </Box>

            {/* List of Licenses */}
            <Box component={Paper} elevation={0} variant="outlined" sx={{ width: "50%" }}>
                {(Object.values(licenseData) as LicensePackage[]).map((pkg, index) => (
                    <Accordion
                        key={pkg.name}
                        disableGutters
                        elevation={0}
                        sx={{
                            '&:before': { display: 'none' },
                            borderBottom: index !== licenses.length - 1 ? '1px solid #e0e0e0' : 'none'
                        }}
                    >
                        {/* The Clickable Header */}
                        <AccordionSummary
                            expandIcon={<ExpandMoreIcon />}
                            id={`panel-${pkg.name}-header`}
                            sx={{
                                '&:hover': { bgcolor: 'action.hover' },
                                px: 3
                            }}
                        >
                            <Box display="flex" alignItems="center" width="100%" flexWrap="wrap" gap={1}>
                                <Typography
                                    variant="subtitle1"
                                    fontWeight="600"
                                    color="primary.main"
                                    sx={{ mr: 2, color: "text.primary" }}
                                >
                                    {pkg.name}
                                </Typography>

                                {pkg.licenses && (
                                    <Chip
                                        label={pkg.licenses}
                                        size="small"
                                        variant="outlined"
                                        color="default"
                                        sx={{ fontSize: '0.7rem', fontWeight: 500 }}
                                    />
                                )}
                            </Box>
                        </AccordionSummary>

                        {/* The Content */}
                        <AccordionDetails sx={{ px: 3, pb: 3, bgcolor: 'secondary.main' }}>
                            {/* Metadata Links */}
                            <Box mb={2} display="flex" flexDirection="column" gap={0.5}>
                                {pkg.repository && (
                                    <Box display="flex" alignItems="center" gap={1}>
                                        <LinkIcon fontSize="small" color="action" />
                                        <Typography variant="body2" component="span" fontWeight="bold">
                                            Source:
                                        </Typography>
                                        <Link
                                            href={pkg.repository}
                                            target="_blank"
                                            rel="noreferrer"
                                            underline="hover"
                                            variant="body2"
                                            sx={{ color: "info.main" }}
                                        >
                                            {pkg.repository}
                                        </Link>
                                    </Box>
                                )}

                                {pkg.publisher && (
                                    <Typography variant="body2">
                                        <strong>Publisher:</strong> {pkg.publisher}
                                    </Typography>
                                )}
                            </Box>

                            {/* License Text Block */}
                            <Box
                                sx={{
                                    border: 1,
                                    borderColor: 'divider',
                                    borderRadius: 1,
                                    bgcolor: 'background.paper',
                                    overflow: 'hidden'
                                }}
                            >
                                <Box
                                    sx={{
                                        bgcolor: 'grey.100',
                                        px: 2,
                                        py: 1,
                                        borderBottom: 1,
                                        borderColor: 'divider',
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: 1
                                    }}
                                >
                                    <CodeIcon fontSize="small" color="action" />
                                    <Typography variant="caption" fontWeight="bold" color="text.secondary" textTransform="uppercase">
                                        Full License Text
                                    </Typography>
                                </Box>

                                <Box
                                    component="pre"
                                    sx={{
                                        p: 2,
                                        m: 0,
                                        overflowX: 'auto',
                                        fontFamily: 'Monospace',
                                        fontSize: '0.75rem',
                                        whiteSpace: 'pre-wrap', // Wraps text so no horizontal scroll
                                        color: 'text.primary',
                                        maxHeight: '400px', // Prevent extremely long licenses from taking too much space
                                        overflowY: 'auto'
                                    }}
                                >
                                    {pkg.licenseText || 'No license text provided.'}
                                </Box>
                            </Box>
                        </AccordionDetails>
                    </Accordion>
                ))}
            </Box>
        </Box>
    );
};

export default Licenses;